---
title: "Introduction to fitting multiple outbreak model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to fitting multiple outbreak model}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(dev="png", collapse = T, comment = "#>")
options(tibble.print_min = 4L, tibble.print_max = 4L)

```

## Introduction

Load library,

```{r}
library("cr0eso")
```

## Create simulated data

The package will expect the data in a certain format, such as the following,

```{r}
# maximum time
tmax <- 5
n_outbreaks <- 2
outbreak_cases <- matrix(c(0,0,1,2,3,0,0,2,4,5),ncol=2)
outbreak_sizes <- c(100,100)
```


## Constructing priors

Parameterisation of the priors are kept in the list `prior_list` and can be updated shown below,

```{r}
# define list of priors
new_prior_list <- cr0eso::prior_list

# update mean of r0 prior to be 2
new_prior_list$r0_mean <- 2
```


## Fit model

Fit model with no intervention and updated priors,

```{r}

fit <- cr0eso::seir_model_fit(tmax,n_outbreaks,outbreak_cases,outbreak_sizes,
                       intervention_switch = FALSE,
                       priors = new_prior_list)
```

## Plot model output

```{r}
# Extract the posterior samples to a structured list:
posts <- rstan::extract(fit$model)

extracted_posts <- hom_extract_posterior_draws(posts) # get object of incidence and zeta
result <- hom_plot_r0_by_location(extracted_posts=extracted_posts)

# plot results
result$plot
```

## Plot model fit to incidence

```{r}
extracted_posts <- hom_extract_posterior_draws(posts) # get object of incidence and r0
result <- hom_plot_incidence_by_location(extracted_posts=extracted_posts,
                                         outbreak_cases = outbreak_cases)
# plot results
result$plot
```
